### ISSUE TITLE
Браузер не может подключится к серверу при переходе по ссылке на страницу приложения

### ISSUE THREAD

**Issue by NastiaUzdemir** [NastiaUzdemir/webtest#1]
# Описание
Браузер не может подключится к серверу при переходе по ссылке на страницу приложения

# Локация дефекта
Браузеры Safari, Google, Яндекс

# Шаги воспроизведения

1. Запустить app-order.jar через команду в терминале java -jar app-order.jar

* Ожидаемый результат: открытие приложения 
* Фактический результат: уведомление об ошибке: в браузере Safari «адрес страницы не верен»
# Скрины
<img width="659" alt="Снимок экрана 2024-03-23 в 19 59 11" src="https://github.com/NastiaUzdemir/webtest/assets/47664011/18912f83-9d72-4e33-b880-117a91fe4fdc">

<img width="1210" alt="Снимок экрана 2024-03-23 в 19 56 05" src="https://github.com/NastiaUzdemir/webtest/assets/47664011/63089a6c-e794-466c-9bb8-8e1a2b164c7d">

# Окружение
* **Операционная система:** MacOS Sonoma 14.2.1
* **Браузер**: Safari, Google, Яндекс

**Comment by andrew-pahomov** [comment]
Для получения доступа к фронту учебного сервиса необходимо запустить джарник из репозитория с условием задачи.      
Такого шага в репорте не вижу.

**Comment by NastiaUzdemir** [comment]
ошибку исправила, всё запустилось
